### ISSUE TITLE
Support pg-9.3 extended constraint error information

### ISSUE THREAD

**Issue by andreak** [impossibl/pgjdbc-ng#10]
The official driver has this now:
https://github.com/pgjdbc/pgjdbc/commit/e9ac5f8d964202ab5d43e401d74dcd76cefd112e

It would be great if NG has it too.

**Comment by kdubb** [comment]
Support has been committed and will be available in the next (0.0.2) release.

To read extended error information, catch a com.impossibl.postgres.jdbc.PGSQLException, instead of a java.sql.SQLException (or cast it as appropriate), and the information for Schema, Table, Column Datatype and Constraint can be read directly from the exception.

**Comment by andreak** [comment]
Great, love it!
