### ISSUE TITLE
schema (namespace) support

### ISSUE THREAD

**Issue by valgog** [impossibl/pgjdbc-ng#11]
Hi, I have not checked it practically, but looking on the code I got an impression, that namespace resolution for types is not really done (for example cache lookups per object name). 

I also have not seen any test cases, that would cover working with objects in different schemas.

(For example standard PostgreSQL JDBC driver does not support namespaces correctly as well)

**Comment by kdubb** [comment]
Can you give an example of how schemas are not supported?  As far as I can tell types are looked on by "oid" and resolved by name using the schema search path.

**Comment by valgog** [comment]
The problem is, that I simply cannot find any reference to schema or namespace inside the cache code (Registry.java)

Also all the `registry.loadType(String)` calls will not really return the correct OIDs when the `search_path` are changed. I also cannot find any code, that will distinguish between types that are have the same names and are located in the different schemas (namespaces).

To summarize, I cannot find the code, that would cope with the following use-cases:
1. `search_path` is changed inside the session (using `SET search_path TO ...` statement)
2. the same type names exist in more then one schema (that includes the types like `text`)

**Comment by kdubb** [comment]
Types are almost always reference by OID.  So Registry.java shouldn't need to reference schema or namespace.

When looking up types by name the driving current takes into account the `search_path` because it uses regular SQL queries to load them.

So...
1) `SET search_path TO ...` is handled by the backend and, from what I can see, is therefore supported
2) To find something in another schema you would a) use schema qualified type names or b) `SET search_path TO ...` and use unqualified references to the type as usual.

My understanding of what you are asking for may be completely off or I am just not seeing an edge case that you have in mind.  Can you provide a concrete example of where the driver fails with regard to namespaces and/or search_paths?

**Comment by vanecanhete** [comment]
I have that problem but calling functions... I didn't read this before so I create a new issue... [https://github.com/impossibl/pgjdbc-ng/issues/92]

**Comment by kdubb** [comment]
Schema's are fully supported as of #354.
