### ISSUE TITLE
COPY support

### ISSUE THREAD

**Issue by ringerc** [impossibl/pgjdbc-ng#136]
(I'm documenting features present in http://github.com/pgjdbc/pgjdc and not in jdbc-ng as part of possible work on enhancing -ng to be a full replacement):

PgJDBC offers a CopyManager API for streaming `COPY ... TO STDOUT` and `COPY ... TO STDIN`. This greatly facilitates bulk-import and bulk-export.

**Comment by kdubb** [comment]
I looked into this when I was implementing the driver originally.  The reason I dropped it from my list of requirements was because I was having trouble coming up with a use case in the actual driver.

I use this feature constantly in psql.  Just never needed it from the Java environment. 

Edit...
Upon reflecting after posting this I realized it might sound like I was questioning its usefulness and wanted it to be clear that I was not.  I guess I was just wondering how people are using it currently.

**Comment by yazun** [comment]
We use this feature (in PgJDBC) all the time it in a distributed environment (>400 cores) to ingest and export the data and lack of this feature is a stopper for us to even try this driver. Otherwise we are based on openjpa for big part of the standard processing.

**Comment by kdubb** [comment]
COPY support will land in 0.9... Anybody wishing to weigh in on the design should see #382
