### ISSUE TITLE
PreparedStatement.setBlob() and setBinaryStream(...) APIs should stream data

### ISSUE THREAD

**Issue by brettwooldridge** [impossibl/pgjdbc-ng#22]
The current implementation reads the entire stream into memory (ByteOutputStream in the case of setBinaryStream()), this will never scale for data that is tens or hundreds of megabytes or multiple-gigabytes in size.

Data should be streamed when the transaction is committed.

**Comment by kdubb** [comment]
Good news... setBlob has always been streamed
Better news... setBinaryStreams are now streamed as well (as of e6b1781b30d05012414ee9ddc12c1be2e90c0955)

**Comment by brettwooldridge** [comment]
Thanks for the work.  I'd like to request that this issue be re-opened, though.  Unfortunately, on github, re-opening an issue requires a project administrator not just a regular user like me.

The statement "The current implementation reads the entire stream into memory..." in the original issue still stands for ResultSets...

From `PGResultSet.java`:

```
public InputStream getBinaryStream(int columnIndex) throws SQLException {
   byte[] data = getBytes(columnIndex);
   if (data == null)
      return null;

    return new ByteArrayInputStream(data);
  }
```

**Comment by kdubb** [comment]
Fixed in 12cb7f8a39e7f0588737c03b7611ecb366c6da2e... let me know it works for you and I'll close this

**Comment by kdubb** [comment]
I assume no news is good news ;)

**Comment by brettwooldridge** [comment]
It's fine to close it for now.  In reality, I haven't been able to thoroughly test it as I am waiting the drop of the DataSource feature to test it in our application server.  If I encounter any issues, I'll reopen.

**Comment by kdubb** [comment]
With regards to setBinaryStream/getBinaryStream et al (excluding Blobs)...

I believe I may need to undo these changes because currently it means the decoder sends references to the network byte buffer which may not be manageable when we upgrade to Netty 4.

This got me really thinking about this feature in general and I have to say, I'm not sure it's needed at all.  "bytea" fields can only be 1GB in size and in almost all methods imaginable require reading the data as a whole into memory.  This means it has to fit into memory.  In the current implementation I could give the driver a FileInputStream to a 750MB file and let it stream it to the server; that's seems nice and relieves memory pressure.  Although, quickly you realize that to ever read that data back... you need to fit all 750MB of data into memory.

This started me thinking about how to get around needing the 750MB of data in memory when reading it back.  There is no standard JDBC solution.  So, nonstandard things like "stream factories" come to mind (i.e. registering a factory for an output stream prior to an execute call) and could pull the "bytea" field off of the wire and incrementally write it to a stream. This would require some interesting changes to the protocol handler that may open up a great number of other problems to solve. All this for a feature that doesn't seem that useful in the end; basically just being able to stream giant amounts of data through the server without ever really using it all the while bringing the server to a screeching halt I imagine.

So, it comes down to, currently we allow streaming the data into the server but not out.  Is this streaming really useful?  Am I missing an obvious use case?  If not, it seems that having parity for streams (must fit in memory going in and coming out) would be better than the current feature set.

**Comment by brettwooldridge** [comment]
As long as streaming in/out works for Blobs, I don't see an issue with BYTEA not streaming.  At least I think not. Regarding Netty 4, Re: network byte buffer references, I don't know if it helps, but there is a way to attach arbitrary objects to a Channel or ChannelHandlerContext now ...
