### ISSUE TITLE
publish 0.7 to maven-central

### ISSUE THREAD

**Issue by andreak** [impossibl/pgjdbc-ng#303]
$subject

**Comment by kdubb** [comment]
I am quite confused... I definitely did this. Trying to figure out where if/where it failed.

**Comment by andreak** [comment]
It's on sonatype but not maven central:
http://central.maven.org/maven2/com/impossibl/pgjdbc-ng/pgjdbc-ng/

**Comment by gsmet** [comment]
Hi,

Apparently Sonatype has issues with the synchronization from OSS to
Central. There is a (long) delay. It's been 6 days we published some
artifacts for Hibernate and they are still not there.

-- 
Guillaume

**Comment by andreak** [comment]
Allrightythen

**Comment by gjdev** [comment]
I have no problem getting artifacts synced to maven central. According to their issue tracker there was indeed a sync issue a week ago, but that talked about hours delay, not days, and has since been resolved. So maybe there's something else going on? Can I suggest to open an issue at https://issues.sonatype.org/projects/OSSRH ? They are usually pretty fast with responding to issues.

**Comment by oscerd** [comment]
The situation is always the same. No 0.7 in maven central.

**Comment by oscerd** [comment]
any news?

**Comment by kdubb** [comment]
I have limited time this week but I am looking into it

**Comment by kdubb** [comment]
@oscerd @andreak I have repeated the release process through oss.sonatype.org. Hopefully it distributes to central correctly this time.

**Comment by oscerd** [comment]
thanks!

**Comment by andreak** [comment]
Jepp, it's there now.
Thanks.
