### ISSUE TITLE
Automated testing of server configurations

### ISSUE THREAD

**Issue by kdubb** [impossibl/pgjdbc-ng#31]
We need a clever strategy for automatically testing the driver against different server versions and configurations (e.g. SSL). Maybe something already exists somewhere? 

Immediately VM's come to mind. Maybe a Maven plugin or ANT task can loop through a set of target VM's and run all tests against each.

**Comment by adamjgray** [comment]
[Vagrant](vagrantup.com) is my first thought for accomplishing this.  You can set up a "fleet" of VM's to run the codebase tests against that should be able to be automated.

**Comment by sehrope** [comment]
Vagrant is an excellent choice for this. Earlier this year I wrote a new SSL socket factory for the legacy Postgres JDBC driver and created a testing VM for it. The VM was then expanded a bit more to allow for testing the legacy SSL functionality of the JDBC driver as well.

Here's how it works: The first time the VM starts up it installs 5 versions of Postgres (8.4 through 9.3), copies over a number of known SSL certificates, and finally maps/forwards each to a well known port (10084, 10090, ... through 10093). The tests for the new socket factory (run via mvn/ant) can then test against all currently supported versions of Postgres and validate things like connecting with a known good/bad certificate.

It's pretty straightforward to understand as it uses the Vagrant shell provisioner (e.g. it just runs a fancy shell script to install everything at first boot). No need to worry about setting up chef/puppet/etc and it just works.

You could probably use it or a variant of the idea for testing the pgjdbc-ng driver as well.

Here's the link: https://github.com/jackdb/pgjdbc-test-vm

**Comment by kdubb** [comment]
I had a look at your code previously while implementing SSL.  I am interested in pulling in your SSL socket factory as well.  Unfortunately I had to use a different system since we connect through netty.

**Comment by sehrope** [comment]
Cool. The socket factory piece would be different given that Netty is non-blocking though I think the core of it (the TrustManager) will remain unchanged. I don't think it'll be much to port it over and will take a peek this week.

As far as testing goes I think it'd be nice to have a green field approach. The SSL testing code in the legacy JDBC driver is kind of ugly as it seems it was based upon testing against a single machine (which by default is localhost). The test VM I put together works great for running the legacy SSL tests but I don't like the test setup itself. For each version of PG you want to test you need to edit the `ssl.properties` file to point it at a different server. Planning it from scratch to test against multiple servers would be a good thing.

**Comment by kdubb** [comment]
Yes.  One of the things I am trying to figure out out to do is parameterize all of our unit tests so they can be run (by a normal "mvn clean install") against a VM with multiple versions installed.  Currently we assume a version of 9.2+ but obviously this grows as new server versions are released.

So, spinning up a Vagrant with multiple servers installed (and each version with/without SSL) is one thing... Then running all unit tests against each of those versions automatically seems to be another.

**Comment by sehrope** [comment]
The preferred approach for repeatedly running tests is to use parameterized tests. Basically you add an annotation (@org.junit.runners.Parameterized) that specifies the list of parameters to use and JUnit will construct your test classes using them.

The socket factory patch I wrote uses it. It returns a list of the servers created in the testing VM. The test class itself only deals with a single server and for simplicity it's assumed that all usernames/passwords are the same across all the test servers: https://github.com/jackdb/pgjdbc/blob/master/org/postgresql/test/ssl/SingleCertValidatingFactoryTest.java#L43

Again I'd only use that as a template to look at as it'd be much cleaner if thought through and built from scratch. A common abstract parent class handling this so that you can run _all_ your tests against _all_ your databases (not just SSL tests) would probably make more sense then putting it directly in the test classes themselves.

**Comment by kdubb** [comment]
Agreed. I am using the @Parameterized  annotation in a number of tests already (actually my converted SSLTest uses it as well).

What I am not clear on is how to "double" parameterize every test in a suite.  Can we put @Parameterized on a TestSuite and choose our server targets that way?  or is does it require a different method.

**Comment by kdubb** [comment]
Travis satisfies this
