### ISSUE TITLE
Unable to connect over domain socket due to exists() check failing

### ISSUE THREAD

**Issue by ajohnson-stripe** [impossibl/pgjdbc-ng#410]
I was trying to use pgjdbc-ng 0.8.2 for connecting over a Unix domain socket recently, but I found that it always fell back to connecting directly to the database host because the `socketFile.exists()` check in `ConnectionUtil` (https://github.com/impossibl/pgjdbc-ng/blob/develop/driver/src/main/java/com/impossibl/postgres/jdbc/ConnectionUtil.java#L195) was always failing.

I built a custom version of the repo that instead did this:
```java
File socketFile = new File(domainAddress.path().replace("unix:", ""));
if (!socketFile.exists()) {
    lastException = new SQLException("Connection Error: unix socket '" + socketFile + "' does not exist", "8001");
    continue;
}
```

And that worked fine. Is my socket somehow misconfigured or this a legitimate bug in `ConnectionUtil`?

**Comment by kdubb** [comment]
Could very well be, I am quite sure it worked during development but I'm now realizing no automated tests currently exist.

**Comment by ajohnson-stripe** [comment]
Alright, I'll take a look at adding a test case for this and send in a pr.

**Comment by kdubb** [comment]
That would be great! 

Note: The Gradle testing is done via Docker and you'll need to bind pg's socket directory into the host in the `postgres-services.yaml` compose file.

**Comment by kdubb** [comment]
I've been looking into this issue and I realized that there shouldn't be any `unix:` in your domain address path.  Do you know where is that coming from?

The format for unix sockets in the URL is here: http://impossibl.github.io/pgjdbc-ng/docs/current/user-guide/#connection-unix. I assume you are getting it somewhat similar to that otherwise it wouldn't parse.

**Comment by ajohnson-stripe** [comment]
I haven't had a chance to look at this in a while, but I'm not totally sure where that was coming from. I was following the format per that link.

**Comment by kdubb** [comment]
I've done quite a bit of testing and I can say for sure that the `exists()` check isn't the cause of connection failures; and your info actually points to an incorrect socket path as well.

As far as your path with a `unix:` prefix, it's a bit perplexing but I did discover that the driver & datasource, when generating a "vanity" URL from parameters, append `unix:` to the socket addresses.  These URLs are generally there because JDBC requires the driver to report a URL regardless of whether a URL was used as the connection "parameter" and they were used to identify connections (because they were as short as possible).

Although I'm not exactly sure if or how how your code was getting one of these "vanity" URLs and using it as a connection, it seemed crazy to me that the URL not be "valid" even if they are more verbose.

So, #438 ensures that the database URL reported. by the driver is now, always, a valid URL representing the connection parameters; regardless of its length.

If that was the cause of your problem, then the PR this should solve it.  If you can attempt it with that PR, it would be great to know the outcome.
