### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by ccleve** [impossibl/pgjdbc-ng#412]
It's not clear from the website or the docs what distinguishes pgjdbc-ng from the default Postgres driver. It would be great to see a paragraph or two that explains the motivation for the project, what the old driver doesn't do, what the new one will do, and some kind of comparison chart between the two.

Also, it would be nice to see the state of the project. In a couple of places the docs say "PGJDBC-NG aims to be a fully compliant JDBC driver..." How close are you to getting there? What's done and not yet done? (Maybe I'll pitch in if there's a feature I need that isn't done.)

**Comment by kdubb** [comment]
From the user guide:
> PGJDBC-NG aims to be a fully compliant JDBC driver for PostgreSQL, implementing JDBC 4.2 onwards. The major goal of the project is to implement all the advanced features of JDBC also supported in PostgreSQL; including composite types, arrays of primitive and composite types, asynchronous notifications, and more.

**Why?** - Because the native driver doesn't support JDBC's API for composite types (e.g. SQLInput/SQLOutput, Struct, etc), and although it supports notifications they are problematic due the their synchronous nature. Identifying and handling extended types through JDBC is not supported either.  Those are some of the major differences.

**State?** - The driver _**is**_ JDBC 4.2 compliant as far as is known.  That being said I'm pretty sure the entirety of the JDBC 4.2 API is not being tested and so inconsistencies probably exist.
