### ISSUE TITLE
RETURNING * suffix improperly appended when preparing statements with return columns

### ISSUE THREAD

**Issue by lihaoyi-databricks** [impossibl/pgjdbc-ng#423]
Full repro:

```scala
@ val datasource = new com.impossibl.postgres.jdbc.PGDataSource()
datasource: com.impossibl.postgres.jdbc.PGDataSource = com.impossibl.postgres.jdbc.PGDataSource@55053f81

@ datasource.setUser("postgres")

@ datasource.setPassword("mysecretpassword")

@ datasource.setDatabaseName("postgres")

@ datasource.setPort(5432)

@ datasource.setHost("localhost")

@ datasource.setSqlTrace(true)


@ val connection = datasource.getConnection
connection: java.sql.Connection = com.impossibl.postgres.jdbc.PGDirectConnection@52e92f6

@ val s = connection.prepareStatement("INSERT INTO Run (build_name) VALUES (?) RETURNING id", Array("id"))
s: java.sql.PreparedStatement = com.impossibl.postgres.jdbc.PGPreparedStatement@5e72c82a

@ s.setTimestamp(1, new java.sql.Timestamp(1564379040372L))
P: null = INSERT INTO Run (build_name) VALUES ($1) RETURNING id RETURNING id
com.impossibl.postgres.jdbc.PGSQLSimpleException: syntax error at or near "RETURNING"
  com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:196)
  com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:173)
  com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:160)
  com.impossibl.postgres.jdbc.PGDirectConnection.execute(PGDirectConnection.java:499)
  com.impossibl.postgres.jdbc.PGPreparedStatement.lambda$describeIfNeeded$1(PGPreparedStatement.java:246)
  com.impossibl.postgres.jdbc.PGDirectConnection.getCachedStatementDescription(PGDirectConnection.java:1531)
  com.impossibl.postgres.jdbc.PGPreparedStatement.describeIfNeeded(PGPreparedStatement.java:244)
  com.impossibl.postgres.jdbc.PGPreparedStatement.resolveType(PGPreparedStatement.java:147)
  com.impossibl.postgres.jdbc.PGPreparedStatement.set(PGPreparedStatement.java:168)
  com.impossibl.postgres.jdbc.PGPreparedStatement.setTimestamp(PGPreparedStatement.java:658)
  com.impossibl.postgres.jdbc.PGPreparedStatement.setTimestamp(PGPreparedStatement.java:643)
  ammonite.$sess.cmd9$.<init>(cmd9.sc:1)
  ammonite.$sess.cmd9$.<clinit>(cmd9.sc)
```

Seems that the `RETURNING id` syntax that's part of the main query conflicts with the `RETURNING *` suffix that's appended during the `describeIfNeeded` call. Any idea how this can be avoided? Or if there is some way to work around?

**Comment by lihaoyi-databricks** [comment]
Seems that any sort of `set*` method on a `prepareStatement` with `RETURNING` in it fails

**Comment by deusaquilus** [comment]
Hey @lihaoyi-databricks. Could you please re-open this based on our conversation? As we have discovered, the `org.postgresql` JDBC driver has had this issue fixed since 9.4.1210.

**Comment by kdubb** [comment]
@deusaquilus Why is the `RETURNING id` being appended manually? According to JDBC the statement should handle it returning those columns, including generating the `RETURNING` clause, and that is exactly what it is doing.

**Comment by deusaquilus** [comment]
@kdubb This is because a user might want to do something like:
```sql
UPDATE ... RETURNING myUdf(id)
```
or
```sql
UPDATE ... RETURNING foo || 'suffix'
```
or even something like
```sql
UPDATE ... RETURNING (SELECT bar FROM baz where baz == id) 
```
all of which are supported by postgres.

So you have to check if the user has already added a `RETURNING` clause themselves
(incidentally, in [Quill](https://github.com/getquill/quill) we support all of these constructs :-)).

**Comment by kdubb** [comment]
@deusaquilus Determining if _user input_ contains one of the myriad of syntaxes for returning clauses is going to be a nightmare.

Wouldn't an easier method be to just execute the statement as a query.  Then these problems vanish.  I believe we essentially do this a number of times in our client code for different reasons.

**Comment by kdubb** [comment]
@deusaquilus I am confused about what is in need of fixing.  I have some changes that recognize a `RETURNING` statement and then skip adding one but I can't make a test that seems to need it.

### Original Issue
@lihaoyi-databricks offered this as the original issue...
```java
connection.prepareStatement("INSERT INTO Run (build_name) VALUES (?) RETURNING id", new String[]{"id"});
```
That can simply be fixed by _not_ adding your own `RETURNING` clause, such as:
```java
connection.prepareStatement("INSERT INTO Run (build_name) VALUES (?)", new String[]{"id"});
```
This is as the JDBC spec. appears to intend it.

### Complex Examples
Your following examples can be done by simply omitting the the list of columns to return...
```java
connection.prepareStatement("UPDATE ... RETURNING myUdf(id)");
connection.prepareStatement("UPDATE ... RETURNING foo || 'suffix'");
connection.prepareStatement("UPDATE ... RETURNING (SELECT bar FROM baz where baz == id)");
```

**If you wanted to use the version of `prepareStatement` that includes a list of _columns_ to return then what would you list as it returning?**

The JDBC spec offers two versions of `prepareStatement` that allow returning values, _both_ of those versions expect you to specify _columns of the table_ not complex return values.

Here is the documentation for the column names version...
```
    * @param columnNames an array of column names indicating the columns
    *     that should be returned from the inserted row or rows
```

Here is the documentation for the column indices version...
```
    * @param columnIndexes an array of column indexes indicating the columns
    *    that should be returned from the inserted row or rows
```
Neither of these refer to allow complex values and I'm not sure how that would even work.

I believe versions of `prepareStatement` that allow specifying return columns are for portability with databases that don't support a returning clause but do return generated columns in their wire protocol.

### Solution
I believe the solution to all of this is to use JDBC API per the specification.  If you want portable code that returns _columns_ you can use the `prepareStatement` as specified. If you want a complex returning clause then add it yourself and use the `prepareStatement` without specifying return columns.

If I am missing something I would love to figure out what it is...
