### ISSUE TITLE
Allow support for `postgresql` in JDBC url

### ISSUE THREAD

**Issue by jamesasefa** [impossibl/pgjdbc-ng#451]
Currently PGJDBC-NG only supports JDBC url's with the following format:

`jdbc:pgsql:<rest_of_url>`

From what I can see, other implementations of JDBC (PGJDBC, Testcontainers, Flyway) resolve the url format as:

`jdbc:postgresql:<rest_of_url>`

Trying the above in pgjdbc-ng throws `java.sql.SQLException: Unsupported database URL`. Our current workaround is to do a string replace before passing the url to the `PGDataSource`, but this is somewhat clunky. 

Wondering if it's possible to have PGJDBC-NG gracefully handle both `pgsql` and `postgresql` in the url?

**Comment by kdubb** [comment]
@jamesasefa While I understand the request, it's probably not something we'll be doing.  We're trying to follow the JDBC specification, which requires a unique scheme for each driver.  Also, some users are including both drivers in the same application. Supporting the same both schemes would run afoul of these requirements & usages.

In the end the small change from 'postgresql' to 'pgsql' is fairly simple and altering the support causes more issues than it solves. For what it's worth, we use libraries (specifically Flyway) without any real issues by just using the `pgsql` scheme to target our driver.

**Comment by kdubb** [comment]
FYI, I'm open to reasons why I'm wrong (e.g. that cause a lot more headache than we experience) and could be persuaded to add this support behind a system setting if it is absolutely needed.

**Comment by kdubb** [comment]
Another note: Our URL format and the format of the mainline driver, while very similar, are not exactly the same. A different scheme does denote with format you should be using quite helpfully.

**Comment by vlsi** [comment]
Even though it might sound crazy, it might be a reasonable (opt-in) feature that is enabled with `-D...`

**Comment by kdubb** [comment]
@vlsi Yes that and then a URL parser 100% compatible with mainline. I think the only "real" thing we support in the URL beyond the mainline is unix socket connections.

**Comment by kdubb** [comment]
@jamesasefa While this is an interesting suggestion it would bring on a couple of things...

1. Tracking closely the mainline driver's URL syntax, because without parity sharing a prefix is useless.
2. It could only be done by an environmental flag otherwise targeting a specific driver would be difficult and have to be done by managing dependencies.
3. It implies a level of parity between the driver's that does not exist

To elaborate on the the 3rd point... While they are targeting the same database there are numerous differences between the drivers that need considered. This could mean changes to the application or SQL queries when switching between drivers and these changes need to be validated through proper testing. In the end I believe the difference is a _good_ thing as it ensures people are using the driver they mean to and all that entails. 

One final note, for small environments that need none of what I described, swapping out prefixes is _very_ easily done and the formats are similar enough that it probably all "just works".
