### ISSUE TITLE
Exception using "SELECT array_agg()"

### ISSUE THREAD

**Issue by skunkiferous** [impossibl/pgjdbc-ng#467]
Hi. I (accidentally) found out about pgjdbc-ng while researching how to replace an OODBMS with PostgreSQL. We would like to do something like the following, as our standard "load all data of customer":

```
CREATE TABLE hello(hello_id serial PRIMARY KEY, greeting TEXT NOT NULL);
CREATE TABLE world(world_id serial PRIMARY KEY, designation TEXT NOT NULL);

INSERT INTO hello(greeting) VALUES('hi');
INSERT INTO world(designation) VALUES('Earth');

SELECT array_agg(hello), array_agg(world) FROM (SELECT * from hello) as hello, (SELECT * FROM world) as world;

```
In short, read many rows from many tables, which have totally different structure, and so cannot be "unioned", into a single SELECT.

Our problem with this in the default PG JDBC driver, is that the array contains org.postgresql.util.PGobject which return the data of a whole table row as a string, which has to be parsed. Our current work-around is converting everything to JSON, as we can use Jackson to do the parsing for us. But this costs time, both on the server and client.

From the description of pgjdbc-ng, I assumed that we could do the same, but get a Struct instead, saving us the String parsing. Unfortunately, what we get instead is an Exception:

```
...
Caused by: java.lang.ClassCastException: com.impossibl.postgres.types.PsuedoType cannot be cast to com.impossibl.postgres.types.ArrayType
        at com.impossibl.postgres.system.procs.Arrays$TxtDecoder.decodeValue(Arrays.java:265)
        at com.impossibl.postgres.system.procs.BaseTextDecoder.decode(BaseDecoders.java:216)
        at com.impossibl.postgres.system.procs.BaseTextDecoder.decode(BaseDecoders.java:194)
        at com.impossibl.postgres.protocol.v30.BufferRowData.getField(BufferRowData.java:145)
        at com.impossibl.postgres.jdbc.ListScroller.getRowField(PGResultSet.java:1858)
        at com.impossibl.postgres.jdbc.PGResultSet.getObj(PGResultSet.java:301)
        at com.impossibl.postgres.jdbc.PGResultSet.getObject(PGResultSet.java:870)
...

```

The test code looks about like:

```
Connection con = ...;
String query = "SELECT array_agg(hello), array_agg(world) FROM (SELECT * from hello) as hello, (SELECT * FROM world) as world;";
Statement stmt = con.createStatement();
ResultSet resultSet = stmt.executeQuery(query);
while (resultSet.next()) {
  for (int i = 1; i <= cols; i++) {
    final Object obj = resultSet.getObject(i);
	// ...
  }
}

```

**Comment by tlf30** [comment]
@skunkiferous I believe (without digging to far into this) that what is returned is an array, not an object. 
```
Connection con = ...;
String query = "SELECT array_agg(hello), array_agg(world) FROM (SELECT * from hello) as hello, (SELECT * FROM world) as world;";
Statement stmt = con.createStatement();
ResultSet resultSet = stmt.executeQuery(query);
while (resultSet.next()) {
  for (int i = 1; i <= cols; i++) {
    final Object[] obj = resultSet.getArray(i);
	// ...
  }
}
```

**Comment by skunkiferous** [comment]
@tlf30 Hi. I just tried it; if I call getArray() instead, I just get the same exception:

```
java.lang.ClassCastException: com.impossibl.postgres.types.PsuedoType cannot be cast to com.impossibl.postgres.types.ArrayType
        at com.impossibl.postgres.system.procs.Arrays$TxtDecoder.decodeValue(Arrays.java:265)
        at com.impossibl.postgres.system.procs.BaseTextDecoder.decode(BaseDecoders.java:216)
        at com.impossibl.postgres.system.procs.BaseTextDecoder.decode(BaseDecoders.java:194)
        at com.impossibl.postgres.protocol.v30.BufferRowData.getField(BufferRowData.java:145)
        at com.impossibl.postgres.jdbc.ListScroller.getRowField(PGResultSet.java:1858)
        at com.impossibl.postgres.jdbc.PGResultSet.getObj(PGResultSet.java:301)
        at com.impossibl.postgres.jdbc.PGResultSet.getVal(PGResultSet.java:294)
        at com.impossibl.postgres.jdbc.PGResultSet.getArray(PGResultSet.java:785)
```

Also note, getArray() returns a java.sql.Array, not a Object[].

I _thought_, since java.sql.Array (as well as Object[]) are effectively Objects anyway in Java, getObject() should be able to return anything. I _believe_ it also does with the standard PostgreSQL JDBC Driver. But I have no clue if this is mandated by the JDBC API, or a "feature" of the PostgreSQL Driver.

**Comment by tlf30** [comment]
Hello @skunkiferous you use the java.sql.Array to get your Object[].
This is an example of using the array_agg function with jdbc: https://stackoverflow.com/questions/32016829/postgresql-array-agg-of-multiple-columns-with-jdbc
(Although the stackoverflow question has nothing to do with yours, the answer is an example of how to do what you are doing)
As for the type issue, I am not sure what pgjdbc-ng is doing, you should be able to get that as an array.

**Comment by kdubb** [comment]
First things first...

This is a deficiency in the type system of the driver as it doesn't properly recognize the `record` pseudo type or its array type.

I've created PR #469 that implements support for them and supports your use case (which has been added as a test case).

About arrays...

In reality pretty much everybody's examples should have worked (after all an array _is_ an `Object`). The type deficiency was getting in the way.

Retrieving with `getArray` is actually the only method that is allowed by the spec but as that is cumbersome and requires calling `free` (which most people forget) we also support the convenient `getObject(index, SomeType[].class)` which you referenced. It should be noted that `getArray` supports complex mapping scenarios to custom types and specific values that may not be supported using the `getObject(int, Class<?>)` method.

When using `getObject(int)`, the results natural type (as specified by JDBC) is `java.sql.Array` so you will get an instance of that type without specifying anything more specific.

Finally...
The query returns a pseudo type `record` which the driver maps to a JDBC `Struct` which is just an ordered set of values.  So you would have always been getting back an array of `Struct` in some fashion, whether you use `getArray`, `getObject(int)` or `getObject(int, Struct[].class)`.

Note that you could make a UDT (i.e. a type that implements `SQLData`) to request strongly typed values instead of using `Struct` and you could then request it with `getObject(int, Class<?>)` as in `rs.getObject(idx, MyAggResult.class)`.

So... something like this will work (with the referenced PR)
```java
Struct[] array = rs.getObject(idx, Struct[].class);
Object[] values = array[0].getAttributes();
```


One final note...
Pseudo types in text mode do not have strong type information which means `Struct.getAttributes()` will return an array of `String`.  The driver strives to stay in binary mode but using `Statement` (i.e. unprepared statements) always returns results in text mode as dictated by PostgresSQL.

With the example in this thread, using `PreparedStatement` will cause `Struct.getAttributes()` to return an `int` and `String` value in the array and using `Statement` will cause `Struct.getAttributes()` to return all `String` values.

**Comment by skunkiferous** [comment]
@kdubb This is good news; we have a dev here (not me), that might have spent by now a month writing code to parse the standard PG driver "text format" back into actual data. With this bug fixed, if we can also combine it with UDTs, we might be able to completely eliminate the "text-parsing" required by the standard driver.
