### ISSUE TITLE
getting the raw underlying data of a resultset

### ISSUE THREAD

**Issue by hoebat** [impossibl/pgjdbc-ng#531]
Is there anyway to get the underlying string that is sent back from Postgres for the execution of a given prepared statement?

**Comment by kdubb** [comment]
Postgres returns a binary structure that _may_ contain string or binary data for each individual field. As such this essentially means "no" you can't because it isn't really a string.

If you want the raw underlying data sent back for a specific column of a result set, you can use `ResultSet.getBytes`.
