### ISSUE TITLE
Copyright statements

### ISSUE THREAD

**Issue by hlinnaka** [impossibl/pgjdbc-ng#66]
The codebase contains a bunch of code copied from the original pgjdbc driver, but the LICENSE file has been changed to say "Copyright (c) 2013, impossibl.com", instead of PostgreSQL Global Development Group. The BSD-style license allows forking and pretty much everything, but the one thing it does require is to keep the original copyright statement intact.

**Comment by kdubb** [comment]
The "bunch of code" is only the unit tests. Dave brought this to my attention a few days ago and it is being corrected.

Just to be clear... again, the only copied code is the unit tests.  At the time I copied them I announced publicly on the list that I was doing so and kept the original PGDG license with them.  When the current license headers were added, it was done using an automated script which stripped off the original license from each file instead of just adding the new one.  Just an oversight, nothing nefarious was going on.

**Comment by hlinnaka** [comment]
On 01/29/2014 11:48 AM, Kevin Wooten wrote:

> The "bunch of code" is only the unit tests. Dave brought this to my
> attention a few days ago and it is being corrected.

At least the XA code is also copied. I don't know what else if anything, 
but that's the part I'm most familiar with.

> Just to be clear... again, the only copied code is the unit tests.
> At the time I copied them I announced publicly on the list that I was
> doing so and kept the original PGDG license with them.  When the
> current license headers were added, it was done using an automated
> script which stripped off the original license from each file instead
> of just adding the new one.  Just an oversight, nothing nefarious was
> going on.

Sure, I didn't think it was anything nefarious :-).
- Heikki

**Comment by kdubb** [comment]
I'm not sure which code you are referring to exactly.  The only code I didn't initiate was the Datasource/XADatasource implementations.

@jesperpedersen can you add an PGDG copyrights to any code that deserves it that you sourced from the original project?  I am handling the unit test files.

**Comment by jesperpedersen** [comment]
@hlinnaka Sorry about that, Heikki
@kdubb PR 67

**Comment by davecramer** [comment]
Probably should say 2004-2014 as I will be updating the copyright soon

Guess there is no way to just say 2004-current year ?

Dave Cramer

**Comment by kdubb** [comment]
I believe all grafted code has been updated

**Comment by hlinnaka** [comment]
Thanks. I hate to be a pedant, but I believe that's still not quite right. The license blurp in the files has this:
- \* Neither the name of impossibl.com nor the names of its contributors may
  - be used to endorse or promote products derived from this software
  - without specific prior written permission.

The original license blurp in the pgjdbc driver says "PostgreSQL Global Development Group" instead of impossibl.com above. The license requires the original text to be included.

My recommendation would be to remove all the new license texts, and put back the original in file called LICENSE, like it is in the pgjdbc driver. It makes no practical difference in what you can or cannot do with the code, so better keep it simple. If there are two otherwise identical licenses, but one says PGDG but the other one says impossibl.com, that's just confusing. After all, PGDG isn't a strictly defined legal entity, impossibl.com is part the Group just by the feat of writing the new driver.

**Comment by kdubb** [comment]
I followed @jesperpedersen lead and used just the copyright

If that's wrong, I can fix... but I have to disagree with your assertion about the licenses.  Most, if not all, of the files brought from the original project are significantly reworked and were done so by an actual company; as in a legally defined entity.

Your assertion that just by writing the driver we become part of PGDG has to be completely incorrect.  If it were the case that since PGDG isn't a strictly defined legal entity writing a driver automatically included me in that entity then PGDG could assert rights over any code I wrote.  Which obviously isn't right.

I have no problem attributing code to those who created it, obviously, but as we are a legal entity that wrote all the original code in the driver (which is > 90% or more) we must legally protect ourselves from those that decide to use it.  Which is the general intent of the BSD license.

So if you'd like me to add both license/copyright statements in full I can do that; but to remove ours seems quite illogical.

**Comment by hlinnaka** [comment]
> Your assertion that just by writing the driver we become part of PGDG has to be completely incorrect. If it were the case that since PGDG isn't a strictly defined legal entity writing a driver automatically included me in that entity then PGDG could assert rights over any code I wrote. Which obviously isn't right.

PGDG is a fuzzy concept. It's used to refer to everyone who has contributed, to avoid listing every single contributor individually. See also the main project's Developer FAQ: https://wiki.postgresql.org/wiki/Developer_FAQ#Do_I_need_to_sign_a_copyright_assignment.3F.

> I have no problem attributing code to those who created it, obviously, but as we are a legal entity that wrote all the original code in the driver (which is > 90% or more) we must legally protect ourselves from those that decide to use it. Which is the general intent of the BSD license.

Note that the license text says "name of impossibl.com nor the names of its contributors", and "IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS ...". impossibl.com is definitely a copyright owner and a contributor. Mentioning the name explicitly doesn't make any difference.

> So if you'd like me to add both license/copyright statements in full I can do that; but to remove ours seems quite illogical.

Well, the PostgreSQL license has to be there, and I can't stop you from adding a new license, but it makes no difference from a legal point of view. It's not what people usually do when starting a new project or forking an old one, and it seems silly to include two copies of essentially the same license. So, please reconsider, for the sake of simplicity.

PS. Please note that I'm talking specifically about the license text. I don't have a problem with adding a one-line copyright notice to every file. That's not strictly required from a legal point of view either, but it's just one line. And unlike adding a whole new license blurp, it is a common practice to add copyright notices for major contributions in many projects, and it's well understood what it means to have several copyright holders listed (unlike with licenses, where you have to actually read both licenses to figure out how they apply (which is not too difficult when they're word-by-word identical except for the named entity, but still...))
